### ISSUE TITLE
configuration's all_server_sockets should reduce the ipaddress of ipv4 and ip6 into a single one

### ISSUE THREAD

**Issue by Scarletsang** [Sangyao42/web_serv#40]

**Comment by Scarletsang** [comment]
I realized this is not an issue to "fix". Rather it is something that the parser will check and optimise for. After the parse tree is generated, there will be checker that checks if the tree make sense semantically (the parser earlier only checks for syntactical errors), and in that part it will make sure that if there are multiple listens in the same server block with different type, they will be reduced to just a single listen.

**Comment by Sangyao42** [comment]
> I realized this is not an issue to "fix". Rather it is something that the parser will check and optimise for. After the parse tree is generated, there will be checker that checks if the tree make sense semantically (the parser earlier only checks for syntactical errors), and in that part it will make sure that if there are multiple listens in the same server block with different type, they will be reduced to just a single listen.

Make sense. just make sure this single listen's family should be saved different than "only listen at IPV4" and "only listen at IPV6".

**Comment by Sangyao42** [comment]
> > I realized this is not an issue to "fix". Rather it is something that the parser will check and optimise for. After the parse tree is generated, there will be checker that checks if the tree make sense semantically (the parser earlier only checks for syntactical errors), and in that part it will make sure that if there are multiple listens in the same server block with different type, they will be reduced to just a single listen.
> 
> Make sense. just make sure this single listen's family should be saved different than "only listen at IPV4" and "only listen at IPV6".

listen 8080 will make the socket listen on ipv4 address with port 8080
listen  [::]:8080 will make the socket listen on ipv6 address with port 8080
listen www.hi.com:8080 will make the socket listen on ipv6 address with port 8080 now because getaddrinfo() will AF_UNSPEC flag will resolve www.hi.com to something like[xxxx:...:xxxx]:8080.
