### ISSUE TITLE
Req & Res Implementation

### ISSUE THREAD

**Issue by Sangyao42** [Sangyao42/web_serv#56]

**Comment by euns-kim** [comment]
I reviewed with the logic together.

Some comments: 

1) Should we not send 415 when unsupported media type for the cgi get request?

2) I guess you used assert() where it should have gone wrong when it is designed as intended, right? How about exit(1) for exec fail? Guess it will be modified.

3) I will also think about how the response parsing should be for the cgi. When you read headers for tmp response I guess there should be only one "\r\n"?

**Comment by Sangyao42** [comment]
> I reviewed with the logic together.
> 
> Some comments:
> 
> 1. Should we not send 415 when unsupported media type for the cgi get request?
> 2. I guess you used assert() where it should have gone wrong when it is designed as intended, right? How about exit(1) for exec fail? Guess it will be modified.
> 3. I will also think about how the response parsing should be for the cgi. When you read headers for tmp response I guess there should be only one "\r\n"?

1. Any error return by cgi is 500.
2. assert() check expected values. It does not nest with the logic.
3. The syntax could be self-defined in simple cases. Right now only get a string for "content-type" followed by "/r/n/r/n"
